[build]
  publish = "packages/web/out"
  command = "yarn build:prod"

[dev]
  command = "yarn dev"

[functions]
  directory = "packages/functions/src"
  external_node_modules = ["express"]
  node_bundler = "esbuild"

# Enable this plugin to run tests on Netlify
#[[plugins]]
#  package = "netlify-plugin-cypress"
#  [plugins.inputs]
#    record = true
#    start = "yarn percy exec:start"
#    configFile = "packages/web/cypress.netlify.json"