[build]
  ignore = "git diff --quiet HEAD^ HEAD ."
  command = "yarn test:e2e && yarn build-storybook"
  publish = "storybook-static"

[build.environment]
  NETLIFY_USE_YARN = "true"

[[plugins]]
  package = "netlify-plugin-cypress"