[build]
  publish = "lrns-web/out"
  command = "./install-aws.sh && yarn build:prod"

[[plugins]]
package = "/packages/content-fs-cache-netlify-plugin"

[functions]
  directory = "packages/functions"
