name: 🧪 E2E Tests - Cypress

on:
  push:
    branches: [main]
  pull_request:
    types: [labeled, opened, synchronize]

jobs:
  lr-e2e-tests:
    uses: last-rev-llc/workflows/.github/workflows/e2e.yml@main
    with:
      provider: 'netlify' # Or 'vercel'
      parallel-jobs: 10
    secrets:
      CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      SITE: ${{ secrets.SITE }}
