name: Starter E2E Tests

on:
  push:
    branches: [main]
    paths:
      - 'examples/lastrev-next-starter/**'
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
    paths:
      - 'examples/lastrev-next-starter/**'
  # Used as a webhook event for publish success actions
  repository_dispatch:
  # Used to fire tests manually from Github
  workflow_dispatch:
    inputs:
      baseURL:
        default: 'https://starter.lastrev.com'
        type: string
        description: 'Base URL to run the test against'
        required: true
      environment:
        description: 'Environment to run the tests against'
        type: environment
        required: false
      parallelCount:
        description: 'Count of parallel instances to use'
        type: environment
        required: false

jobs:
  check-label:
    if: github.actor != 'github-actions[bot]'
    defaults:
      run:
        working-directory: ./examples/lastrev-next-starter
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.14.0-slim-chrome99-ff97
      options: --user 1001
    steps:
      # Enforce label on PR to prevent unnecesary testing
      - name: Enforce labels
        uses: mheap/github-action-required-labels@v1
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 1
          labels: 'qa-ready'
