name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      baseURL:
        default: 'https://starter.lastrev.com'
        type: string
        description: 'Base URL to run the test against'
        required: true
      environment:
        description: 'Environment to run the tests against'
        type: environment
        required: false

jobs:
  install:
    defaults:
      run:
        working-directory: ./examples/lastrev-next-starter
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.14.0-slim-chrome99-ff97
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: ./examples/lastrev-next-starter/node_modules/.cache/turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./examples/lastrev-next-starter
          project: ./packages/web
          runTests: false

      # report machine parameters
      - run: npx cypress info
      # - run: node -p 'os.cpus()'
      # - run: yarn types
      # - run: yarn lint
      # - run: yarn test:unit:ci
      # - run: yarn turbo run build

      # - name: Save build folder
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: build
      #     if-no-files-found: error
      #     path: build

  ui-chrome-tests:
    defaults:
      run:
        working-directory: ./examples/lastrev-next-starter
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.14.0-slim-chrome99-ff97
      options: --user 1001
    needs: install
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]

    steps:
      # - name: Set base URL
      #   id: baseURL
      #   run: |
      #     BASE_URL=${{ github.event.inputs.baseURL }}
      #     echo "::set-output name=value::${BASE_URL:-"https://starter.lastrev.com"}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: ./examples/lastrev-next-starter/node_modules/.cache/turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-

      # - name: Download the build folders
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: build
      #     path: build

      - name: 'Website Tests - Chrome'
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./examples/lastrev-next-starter
          project: ./packages/web
          command-prefix: 'percy exec -- npx'
          # wait-on: http://localhost:5338/percy/healthcheck
          # wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: 'UI - Chrome'

        env:
          # CYPRESS_BASE_URL: ${{ steps.baseURL.outputs.value }}
          CYPRESS_BASE_URL: 'https://starter.lastrev.com'
          NODE_ENV: ${{ github.event.inputs.environment }}
          CYPRESS_PROJECT_ID: ${{ secrets.STARTER_CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.STARTER_CYPRESS_RECORD_KEY }}
          PERCY_TOKEN: ${{ secrets.STARTER_PERCY_TOKEN }}
          PERCY_PARALLEL_NONCE: '${{ github.event_name }}-${{ github.sha }}'
          PERCY_PARALLEL_TOTAL: 5
          COMMIT_INFO_BRANCH: ${{ github.head_ref }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
